apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../llama-stack
  - ../../../ui

namespace: blackjack-ai-demo

labels:
  - pairs:
      app.kubernetes.io/name: blackjack-ai-game
      app.kubernetes.io/instance: mistral-demo
      app.kubernetes.io/component: ai-gaming-demo
      deployment.mode: mistral

replacements:
- source:
    kind: ConfigMap
    name: run-config-mistral
  targets:
  - select:
      kind: Deployment
      name: llamastack-deployment
    fieldPaths:
    - spec.template.spec.volumes.[name=run-config-volume].configMap.name

configMapGenerator:
- name: blackjack-config
  literals:
    - VITE_USE_LOCAL_AI=false
    - VITE_AI_PROVIDER=mistral
    - VITE_LLAMA_STACK_ENDPOINT=http://llamastack-service:8321
    - VITE_MISTRAL_AI_KEY=62fd2860ea715b8dfed124b80dd31715
  behavior: replace

secretGenerator:
- name: blackjack-secrets
  literals:
    - MISTRAL_API_TOKEN=62fd2860ea715b8dfed124b80dd31715
  behavior: replace

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: llamastack-deployment
  spec:
    template:
      spec:
        containers:
        - name: llamastack
          env:
          - name: MISTRAL_URL
            value: "https://mistral-small-24b-w8a8-maas-apicast-production.apps.prod.rhoai.rh-aiservices-bu.com:443/v1"
          - name: MISTRAL_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: blackjack-secrets
                key: MISTRAL_API_TOKEN

images:
- name: quay.io/redhat-et/llama
  newTag: vllm-0.2.2
