apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: llamastack-route
  labels:
    app: llamastack
spec:
  to:
    kind: Service
    name: llamastack-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect