# Production environment patches
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-frontend
  namespace: blackjack-ai-demo
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: blackjack-frontend
        env:
        - name: VITE_USE_LOCAL_AI
          value: "false"  # Use remote vLLM in production
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"