apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: blackjack-ai-game
  namespace: blackjack-ai-demo
  labels:
    app: blackjack-ai-game
spec:
  output:
    to:
      kind: ImageStreamTag
      name: blackjack-ai-game:latest
  source:
    type: Git
    git:
      uri: https://github.com/your-username/blackjack-ai-game.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
  - type: ImageChange
    imageChange: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: blackjack-ai-game
  namespace: blackjack-ai-demo
  labels:
    app: blackjack-ai-game
spec:
  lookupPolicy:
    local: true