apiVersion: v1
kind: Secret
metadata:
  name: blackjack-secrets
  namespace: blackjack-ai-demo
type: Opaque
stringData:
  # vLLM API Key - Replace with your actual API key
  VITE_REMOTE_AI_KEY: "YOUR_API_KEY_HERE"
  
  # MAAS-related environment variables
  MAAS_API_KEY: "YOUR_MAAS_API_KEY_HERE"
  MAAS_ENDPOINT: "YOUR_MAAS_ENDPOINT_HERE"
  MAAS_MODEL: "YOUR_MAAS_MODEL_HERE"